# Generated by Django 4.2.2 on 2023-06-21 03:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="newUser",
            new_name="User",
        ),
    ]
